apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 2
  template:
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "public.ecr.aws/n2d8l6y5/web-app:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: kustom-config-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"