apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  template:
    spec:
      containers:
      - name: mycontainer
        image: "public.ecr.aws/n2d8l6y5/web-app:f0c8ad778352c0cc0e23fc7844089e20161bdec6"
